Repository bluewave-labs/LangRoute, pull requests merged in 2025-08, with the labels that each got.

#26 🔐 Initial Authentication System – Credentials + Google OAuth
  .env.example
  .gitignore
  components.json
  docker/docker-compose.db.yml
  middleware.ts
  package-lock.json
  package.json
  prisma/schema.prisma
  prisma/seed.ts
  src/app/(admin)/middleware.ts
  src/app/(auth)/components/AuthFormWrapper.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/page.tsx
  src/app/(dashboard)/page.tsx
  src/app/403/page.tsx
  src/app/_api/auth/route.ts
  src/app/_api/usage/route.ts
  src/app/api/admin/middleware.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/forgot/route.ts
  src/app/api/auth/me/route.ts
  src/app/api/auth/register/route.ts
  src/app/api/auth/reset/route.ts
  src/app/api/usage/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/components/auth/GoogleSignInButton.tsx
  src/components/form/FormInput.tsx
  src/components/index.ts
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/hooks/data/index.ts
  src/hooks/data/useSessionUser.ts
  src/hooks/index.ts
  src/lib/auth.ts
  src/lib/authOptions.ts
  src/lib/config/routesConfig.ts
  src/lib/models/Auth.ts
  src/lib/models/User.ts
  src/lib/models/index.ts
  src/lib/types/global.d.ts
  src/lib/types/next-auth.d.ts
  src/lib/utils/classnames.ts
  src/lib/utils/logger.ts
  src/lib/utils/passwordRules.ts
  src/lib/validation/authSchemas.ts
  src/middleware/matcher.ts
  src/middleware/public-routes.ts
  src/providers/AppProviders.tsx
  src/providers/QueryClientProvider.ts
  src/providers/index.ts
  src/services/auth/index.ts
  src/services/auth/service.ts
  src/services/index.ts
  src/services/system/errorService.ts
  src/types/global.d.ts
Labels: Core, 🔥Critical, Backend

#25 Models: add page and modal
  package-lock.json
  package.json
  src/app/(dashboard)/models/components/ModelCreateModal.tsx
  src/app/(dashboard)/models/components/ModelsContent.tsx
  src/app/(dashboard)/models/components/ModelsTable.tsx
  src/app/(dashboard)/models/components/ModelsTableBody.tsx
  src/app/(dashboard)/models/components/ModelsTableHeader.tsx
  src/app/(dashboard)/models/page.tsx
  src/components/index.ts
  src/components/ui/badge.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
  src/components/ui/multiple-selector.tsx
Labels: Core, Frontend

#24 uncomment middleware matcher patern
  middleware.ts
  prisma/schema.prisma
  src/app/_api/apikeys/route.ts
  src/app/_api/chat/route.ts
  src/lib/errors.ts
  src/lib/middleware/apiKey.ts
Labels: Core, Backend

#45 Feat/app overhaul
  .prettierrc
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
  components.json
  docs/architecture.md
  docs/getting-started.md
  package-lock.json
  package.json
  src/app/(client)/(core)/admin/limits/components/AccessKeyLimitDialog.tsx
  src/app/(client)/(core)/admin/limits/components/AccessKeyLimitsTable.tsx
  src/app/(client)/(core)/admin/limits/components/BudgetSummaryCards.tsx
  src/app/(client)/(core)/admin/limits/components/OrgLimitsForm.tsx
  src/app/(client)/(core)/admin/limits/page.tsx
  src/app/(client)/(core)/analytics/page.tsx
  src/app/(client)/(core)/dashboard/components/ActionCard.tsx
  src/app/(client)/(core)/dashboard/components/DashboardCard.tsx
  src/app/(client)/(core)/dashboard/components/DashboardContent.tsx
  src/app/(client)/(core)/dashboard/components/GetStartedCard.tsx
  src/app/(client)/(core)/dashboard/page.tsx
  src/app/(client)/(core)/key-management/page.tsx
  src/app/(client)/(core)/layout.tsx
  src/app/(client)/(core)/logs/page.tsx
  src/app/(client)/(core)/models/page.tsx
  src/app/(client)/components/auth/GoogleAuthButton.tsx
  src/app/(client)/components/common/Buttons.tsx
  src/app/(client)/components/common/PageHeader.tsx
  src/app/(client)/components/common/ThemeToggle.tsx
  src/app/(client)/components/index.ts
  src/app/(client)/components/layout/Logo.tsx
  src/app/(client)/components/layout/PageHeader.tsx
  src/app/(client)/components/layout/SectionHeader.tsx
  src/app/(client)/components/layout/Sidebar.tsx
  src/app/(client)/hooks/index.ts
  src/app/(client)/hooks/ui/useMobile.ts
  src/app/(client)/providers/Providers.tsx
  src/app/(client)/providers/ThemeProvider.tsx
  src/lib/auth.ts
  src/lib/config/nav.ts
  src/shadcn-ui/avatar.tsx
  src/shadcn-ui/button.tsx
  src/shadcn-ui/dropdown-menu.tsx
  src/shadcn-ui/form.tsx
  src/shadcn-ui/index.ts
  src/shadcn-ui/progress.tsx
  src/shadcn-ui/sidebar.tsx
  src/shadcn-ui/skeleton.tsx
  src/shadcn-ui/switch.tsx
  src/shadcn-ui/tabs.tsx
  src/shadcn-ui/tooltip.tsx
  tailwind.config.js
  tsconfig.json
Labels: Core, Frontend, Backend

#49 Integrate button standardization
  src/app/(client)/(auth)/components/AuthFormWrapper.tsx
  src/app/(client)/(auth)/login/page.tsx
  src/app/(client)/(auth)/password/forgot/page.tsx
  src/app/(client)/(auth)/register/page.tsx
  src/app/(client)/(core)/dashboard/components/DashboardCard.tsx
  src/app/(client)/(core)/dashboard/components/DashboardContent.tsx
  src/app/(client)/(core)/dashboard/components/GetStartedCard.tsx
  src/app/(client)/(core)/key-management/components/KeyCreateModal.tsx
  src/app/(client)/(core)/key-management/components/KeyManagementContent.tsx
  src/app/(client)/(core)/key-management/components/KeysTableBody.tsx
  src/app/(client)/(core)/models/components/ModelCreateModal.tsx
  src/app/(client)/(core)/models/components/ModelsContent.tsx
  src/app/(client)/(core)/models/components/ModelsTableBody.tsx
  src/app/(client)/403/page.tsx
  src/app/(client)/components/auth/GoogleAuthButton.tsx
  src/app/(client)/components/common/Buttons.tsx
  src/app/(client)/components/common/ThemeToggle.tsx
  src/app/(client)/components/form/FormInput.tsx
  src/app/(client)/components/input/SearchBar.tsx
  src/app/(client)/components/layout/SectionHeader.tsx
  src/app/(client)/components/layout/Sidebar.tsx
  src/app/(client)/globals.css
  src/app/(client)/loading.tsx
  src/app/(client)/not-found.tsx
  src/app/(client)/providers/ThemeProvider.tsx
  src/app/(client)/unauthorized.tsx
  src/app/(server)/services/auth/service.ts
  src/app/(server)/services/system/errorService.ts
  src/shadcn-ui/form.tsx
  src/shadcn-ui/progress.tsx
  src/shadcn-ui/switch.tsx
  src/shadcn-ui/tabs.tsx
  src/shadcn-ui/tooltip.tsx
Labels: Frontend

#50 Task/button standardization
  next.config.ts
  package.json
  public/assets/icons/langroute-mark.png
  src/app/(client)/(auth)/components/AuthFormWrapper.tsx
  src/app/(client)/(auth)/login/page.tsx
  src/app/(client)/(auth)/password/forgot/page.tsx
  src/app/(client)/(auth)/register/page.tsx
  src/app/(client)/(core)/analytics/page.tsx
  src/app/(client)/(core)/dashboard/components/DashboardCard.tsx
  src/app/(client)/(core)/dashboard/components/DashboardContent.tsx
  src/app/(client)/(core)/dashboard/components/GetStartedCard.tsx
  src/app/(client)/(core)/key-management/components/KeyCreateModal.tsx
  src/app/(client)/(core)/key-management/components/KeyManagementContent.tsx
  src/app/(client)/(core)/key-management/components/KeysTableBody.tsx
  src/app/(client)/(core)/logs/page.tsx
  src/app/(client)/(core)/models/components/ModelCreateModal.tsx
  src/app/(client)/(core)/models/components/ModelsContent.tsx
  src/app/(client)/(core)/models/components/ModelsTableBody.tsx
  src/app/(client)/403/page.tsx
  src/app/(client)/components/auth/GoogleAuthButton.tsx
  src/app/(client)/components/common/ButtonGroup.tsx
  src/app/(client)/components/common/Buttons.tsx
  src/app/(client)/components/common/ConditionalButtons.tsx
  src/app/(client)/components/common/NavButton.tsx
  src/app/(client)/components/common/ThemeToggle.tsx
  src/app/(client)/components/form/FormInput.tsx
  src/app/(client)/components/index.ts
  src/app/(client)/components/input/SearchBar.tsx
  src/app/(client)/components/layout/Logo.tsx
  src/app/(client)/components/layout/SectionHeader.tsx
  src/app/(client)/components/layout/Sidebar.tsx
  src/app/(client)/globals.css
  src/app/(client)/loading.tsx
  src/app/(client)/not-found.tsx
  src/app/(client)/page.tsx
  src/app/(client)/providers/ThemeProvider.tsx
  src/app/(client)/unauthorized.tsx
  src/app/(server)/api/apikeys/[id]/route.ts
  src/app/(server)/api/usage/route.ts
  src/app/(server)/services/auth/service.ts
  src/app/(server)/services/index.ts
  src/app/(server)/services/system/errorService.ts
  src/app/(server)/services/usage/service.ts
  src/shadcn-ui/form.tsx
  src/shadcn-ui/progress.tsx
  src/shadcn-ui/switch.tsx
  src/shadcn-ui/tabs.tsx
  src/shadcn-ui/tooltip.tsx
Labels: Core, Frontend
